# Problem 3 Sample Code

This sample code is meant as a guide on how to use PyTorch and how to use the relevant model layers. This not a guide on how to design a network and the network in this example is intentionally designed to have poor performace.

In [15]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

import torch
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd
from torch.utils.data import TensorDataset, Dataset, DataLoader
import seaborn as sns
from sklearn.model_selection import train_test_split

In [16]:
df = pd.read_csv('out.csv')

df = df.replace('',np.nan)
df = df.dropna(axis="rows", how="any")
df = df.drop(columns= "uid")

df_X = df.drop(columns= "label")
for col in df_X:
    df_X[col] = [(element - np.mean(df_X[col])) / np.std(df_X[col]) for element in df_X[col]]
print("===dataframe=== \n {}".format(df))
X = np.array(df_X)
y = np.array(df["label"])

# def normalize(x):
#     x = np.asarray(x)
#     return (x - x.min()) / (np.ptp(x))
# X_normed = []
# for i in range(0, len(X)):
#     X_normed.append(X[i])
# # X = (X - X.mean())/(X.std())
# print(" - NORMALIZED  X \n {} - ".format(X))


train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2)
# print(" pre TRAIN X \n {}".format(train_X))

train_X = torch.tensor(train_X, dtype=torch.float32)
# print("TENSOR  X \n {}".format(train_X))
train_y = torch.tensor(train_y, dtype=torch.long)
# 80/20 x values as floats
test_X = torch.tensor(test_X, dtype=torch.float32)
test_y = torch.tensor(test_y, dtype=torch.long)

train_dataset = TensorDataset(train_X, train_y)
test_dataset = TensorDataset(test_X, test_y)

train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=32, shuffle=True) 

print ("x \n{}".format(df))
print ("y \n{}".format(df))

# x_train = torch.tensor(train[['chi','lin_reg','lin_reg_chi','stddev_step_speed']].copy().to_numpy(), dtype=torch.float32)
# y_train = torch.tensor(train['label'].copy().to_numpy(), dtype=torch.long)
# x_test = torch.tensor(train[['chi','lin_reg','lin_reg_chi','stddev_step_speed']].copy().to_numpy(), dtype=torch.float32)
# y_test = torch.tensor(train['label'].copy().to_numpy(), dtype=torch.long)
# train_dataset = TensorDataset(x_train, y_train)
# test_dataset = TensorDataset(x_test, y_test)

===dataframe=== 
        label           chi   lin_reg  lin_reg_chi  stddev_step_speed
0          0  8.474767e+04  0.992533     0.988869          17.360221
1          0  2.097220e+04  0.973844     1.938908          17.308306
2          0  2.356781e+04  0.894242     6.604954          17.300169
3          0  8.100880e+03  0.967026     5.758685          17.376369
4          0  5.593839e+05  0.000296     1.512429          17.205146
...      ...           ...       ...          ...                ...
16075      0  4.669320e+05  0.999245     0.867075          18.036484
16076      0  1.375967e+06  0.999707     1.345129          26.151765
16077      0  2.235552e+06  0.998892     3.587700          23.801682
16078      0  6.701228e+05  0.998953     0.680709          16.319528
16079      0  6.096492e+05  0.999056     7.286809          30.031311

[16013 rows x 5 columns]
x 
       label           chi   lin_reg  lin_reg_chi  stddev_step_speed
0          0  8.474767e+04  0.992533     0.988869       

We can convert images to numpy arrays and plot them with matplotlib:

## Network Definition
Let's instantiate a model and take a look at the layers.

In [17]:
model = nn.Sequential(
    nn.Linear(4, 10),
    nn.ReLU(),
    nn.Linear(10, 5),
    nn.ReLU(),
    nn.Linear(5, 2),
    nn.Sigmoid()
)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
# loss_fn = nn.BCELoss()
loss_fn = nn.CrossEntropyLoss()

torch.manual_seed(15552494823729223621)

## Training
We also choose an optimizer and a loss function.

We could write our training procedure manually and directly index the `Dataset` objects, but the `DataLoader` object conveniently creates an iterable for automatically creating random minibatches:

We now write our backpropagation loop, training for 10 epochs.

In [18]:
model.train()

for epoch in range(20):
    for batch_idx, (data, target) in enumerate(train_loader):
        # print("data \n{}".format(data))
        # Erase accumulated gradients
        optimizer.zero_grad()

        # Forward pass
        output = model(data)
        # print(" -- OPUTPUT -- \n{}".format(output))
        # output = output.flatten()

        # Calculate loss
        loss = loss_fn(output, target)

        # Backward pass
        loss.backward()
        
        # Weight update
        optimizer.step()

    # Track loss each epoch
    print('Train Epoch: %d  Loss: %.4f' % (epoch + 1,  loss.item()))

Train Epoch: 1  Loss: 0.6287
Train Epoch: 2  Loss: 0.3648
Train Epoch: 3  Loss: 0.3941
Train Epoch: 4  Loss: 0.3218
Train Epoch: 5  Loss: 0.3689
Train Epoch: 6  Loss: 0.4175
Train Epoch: 7  Loss: 0.4725
Train Epoch: 8  Loss: 0.4067
Train Epoch: 9  Loss: 0.3196
Train Epoch: 10  Loss: 0.3189
Train Epoch: 11  Loss: 0.3150
Train Epoch: 12  Loss: 0.3147
Train Epoch: 13  Loss: 0.4574
Train Epoch: 14  Loss: 0.4110
Train Epoch: 15  Loss: 0.3149
Train Epoch: 16  Loss: 0.3306
Train Epoch: 17  Loss: 0.3165
Train Epoch: 18  Loss: 0.3158
Train Epoch: 19  Loss: 0.3138
Train Epoch: 20  Loss: 0.3142


## Testing
We can perform forward passes through the network without saving gradients.

In [32]:
# Putting layers like Dropout into evaluation mode
model.eval()

test_loss = 0
correct = 0

# Turning off automatic differentiation
with torch.no_grad():
    for data, target in test_loader:
        print(data)
        output = model(data)
        print(output)
        test_loss += loss_fn(output, target).item()  # Sum up batch loss
        pred = output.argmax(dim=1, keepdim=True)  # Get the index of the max class score
        print(pred)
        correct += pred.eq(target.view_as(pred)).sum().item()

test_loss /= len(test_loader.dataset)

print('Test set: Average loss: %.4f, Accuracy : %d/%d (%.4f)' %
      (test_loss, correct, len(test_loader.dataset),
       100. * correct / len(test_loader.dataset)))

tensor([[-0.3892, -0.3151,  1.4743,  0.5516],
        [-0.0349,  0.5717, -0.4669, -1.2871],
        [-0.3996,  0.5878, -0.4641,  0.4955],
        [ 3.7202,  0.5352, -0.3818,  0.9012],
        [-0.3536,  0.5885, -0.4652,  0.5953],
        [-0.4103,  0.5863, -0.4612,  0.6522],
        [-0.1557,  0.5444, -0.4494, -0.0543],
        [-0.1012, -2.5329, -0.4519, -1.2669],
        [-0.1365,  0.5464, -0.0593,  2.9454],
        [-0.3947, -0.2364, -0.0505, -0.7630],
        [-0.4270,  0.5885, -0.4650,  0.5907],
        [-0.4185, -2.4106, -0.4638, -2.1253],
        [-0.3310, -0.2488,  1.2057, -0.3002],
        [-0.3855,  0.5818, -0.4653, -0.5514],
        [-0.1488,  0.5887, -0.4675, -0.5418],
        [ 1.7715,  0.4899, -0.4384,  0.4122],
        [ 5.5774,  0.4773, -0.4611, -1.2996],
        [-0.3361,  0.5825, -0.4675, -1.2554],
        [ 0.2330,  0.0911, -0.4389, -0.7625],
        [ 0.8392,  0.5869, -0.4670, -0.5509],
        [-0.0878, -0.5952,  0.5808, -0.5857],
        [-0.2815,  0.5878, -0.4650

In [27]:
# Creating Output
test = pd.read_csv('test.csv')

df_vals = test.drop(columns= "uid")
for col in df_vals:
    df_vals[col] = [(element - np.mean(df_vals[col])) / np.std(df_vals[col]) for element in df_vals[col]]
print("===dataframe=== \n {}".format(test))

test_X = np.array(df_vals)

test_X = torch.tensor(test_X, dtype=torch.float32)

print(test_X)



===dataframe=== 
            uid           chi   lin_reg  lin_reg_chi  stddev_step_speed
0     lab_19_0  1.226808e+04  0.878979     0.267350          19.661653
1     lab_19_1  2.027183e+05  0.072402   407.576553          18.135286
2     lab_19_2  1.720428e+07  0.998963    27.825655          86.806286
3     lab_19_3  1.170899e+07  0.991160   170.673846          81.682927
4     lab_19_4  1.947901e+07  0.987416     1.985455          10.228939
..         ...           ...       ...          ...                ...
472   lab_42_9  3.893311e+06  0.989693   549.380346          85.433759
473  lab_42_10  9.995795e+04  0.926821   244.652959          32.603626
474  lab_42_11  1.644216e+06  0.952655   132.548405          17.927726
475  lab_42_12  1.712307e+06  0.999726     1.653985          36.955453
476  lab_42_13  2.899105e+05  0.997562    18.285068          46.364285

[477 rows x 5 columns]
tensor([[-0.2431, -0.0117, -0.2071, -0.6031],
        [-0.2309, -3.3169,  0.2097, -0.6731],
        [ 0.85

In [31]:
output = model(test_X)
print(output)
pred = output.argmax(dim=1, keepdim=True)
print(pred)


tensor([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],